import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ConfigProvider, App as AntApp } from "antd";
import { theme } from "@/theme/themeConfig";

const manRope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manRope.variable} h-full antialiased`}
    >
      <ConfigProvider theme={theme}>
        <AntApp>
          <body className="min-h-full flex flex-col">{children}</body>
        </AntApp>
      </ConfigProvider>
      
    </html>
  );
}
